/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ujmuenwjamokbhlkuvim"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbXVlbndqYW1va2JobGt1dmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NDg5MzEsImV4cCI6MjA3NjMyNDkzMX0.l7cHqqzBugccmP-4VdaGRdAd44sDag6cvDW-VAG8X8Q"